SCREEN_HEIGHT, SCREEN_WIDTH = 720, 1080 # Screen dimensions

BUTTON_WIDTH, BUTTON_HEIGHT = 200, 50 # Button dimensions
BUTTON_VERTICAL_OFFSET = BUTTON_HEIGHT + 20
BUTTON_HORIZONTAL_OFFSET = BUTTON_WIDTH + 20
BUTTON_DEFAULT_Y_POS = 200

GRID_CELL_COUNT = 10
GRID_CELL_SIZE = 64 # Cell size
GRID_SIZE = GRID_CELL_SIZE * GRID_CELL_COUNT # Size of entire grid (cell number = 10)
OFFSET_FROM_GRID = 3 # Offset size (from grid border)

SCREEN_TOPBAR_HEIGHT = 80 # Height of topbar (for game buttons)
SCREEN_SIDEBAR_WIDTH = 300 # Width of sidebar (for tower selection/modification)

DEBUG_TEXT_X = GRID_SIZE + 10
DEBUG_TEXT_DEFAULT_HEIGHT = SCREEN_HEIGHT - 20
DEBUG_TEXT_OFFSET = 20

FPS = 60